### ISSUE TITLE
Add selectize.js widget to Project Tags field

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#104]
The project tags field will contain an array of tag IDs. In order to help users select tags while allowing tag ID to be stored, we can add a select widget. For this task, Selectize.js may be sufficient.
# Definition of done
- [x] Schema, publication, subscription, etc have been created for Tags feature
- [x] Project tags field suggests tags as user types
- [x] Tags are stored in Tags collection
- [x] Project `tags` field contains array of selected tags
- [x] When user inputs new tag in `tags` select widget, the tag is created in the Tags collection
- [x] When new tag is created via Selectize widget, the tag appears in the tags list
# Reference

There is a [StackOverflow post](http://stackoverflow.com/questions/24366365/creating-an-item-if-not-already-exists-in-selectize-js-select-box-and-ajax-updat) describing how to add new tags in a Selectize.js callback.

Selectize.js documentation [describes `create` usage in the Options section](https://github.com/selectize/selectize.js/blob/master/docs/usage.md#options).

**Comment by brylie** [comment]
I have almost completed this task. I am just unable to get the newly created tag to appear in the tags field. I have opened an [upstream support request](https://github.com/selectize/selectize.js/issues/992).

**Comment by leosa83** [comment]
Ok nice job and thanks for posting it upstreams.
