### ISSUE TITLE
Add edit feature for existing projects

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#113]
Currently, there is no way to edit existing peojects. Add an edit feature including access control checks.

**Comment by leosa83** [comment]
Should we use a hidden field with ObjectId => if null => insert , if exists => update?
How to do that with quickform @brylie ?

**Comment by Angamanga** [comment]
I can take a look at this one!

**Comment by brylie** [comment]
Great! Go ahead and self-assign :-)

**Comment by leosa83** [comment]
I think we need to move this back to this milestone (0.2)

**Comment by leosa83** [comment]
I self assigned this one @Angamanga , tell me if you already have done lots of coding on this one: but i thionk that it actually is really simple using the quickform semantics

**Comment by Angamanga** [comment]
No, no coding yet... But I was thinking about authorisation? Who should be able to edit? Do we have any kind of authorisation implemented yet?

**Comment by leosa83** [comment]
No authorisation yet , not needed for the 0.2 release

**Comment by leosa83** [comment]
A pull request has been submitted

**Comment by brylie** [comment]
Great! I will review :-)

**Comment by brylie** [comment]
OK, looks good. I suggested some minor changes, for consistency and semantics.
