### ISSUE TITLE
Add "project submitted" page to add project wizard

### ISSUE THREAD

**Issue by 2ECC71** [refugeetech/platform#116]
#### User Story

As a user i want a confirmation that my project has been submitted and added, i also want to view the submitted project.
#### Definition of done
- [ ] When clicking  "Submit Project" button on "add project" page a confirmation page is displayed.
- [ ] Check if project was actually added to database.
- [ ] Confirmation page displays confirmation the project was submitted successfully and a link to the project page.

**Comment by leosa83** [comment]
Great. Will set proper milestone tag.

**Comment by leosa83** [comment]
This is before there are accounts and in time for the possibility to sign up using our meteor 'add Project' form. Instead there will be a webform using typeform.
