### ISSUE TITLE
Add solution field to singleProject page

### ISSUE THREAD

**Issue by 2ECC71** [refugeetech/platform#118]
#### All projects has a "solution" field indicating if the project is primarily a "tech" project or "other" project.

The solution also has a description.
We should add both the type of solution and the description to singleProject.
#### Definition of done
- [ ] Type of solution appears on singleProject page. (solution.isTech) (if true project is "tech", if false project is "other")
- [ ] Solution Description appears on singleProject page (solution.description)

**Comment by leosa83** [comment]
Not part of the 0.2 release because only RT projects will be part of the hub and no need to use a "distinguisher" when there is no other type of projects present
