### ISSUE TITLE
Create schema for Projects collection

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#12]
Create a schema for the Projects collection, based on the initial UML design:
![screenshot](https://cloud.githubusercontent.com/assets/17307/11525601/292a7fca-98dd-11e5-896b-cfd9ed94288b.png)
# Acceptance criteria
- [x] Schema includes all fields from initial design
- [x] Field names are defined in camelCase
- [x] Data type is indicated for each field
- [ ] Validation is added for remoteId fields
- [ ] [optional] AutoForm elements are defined for special field types

**Comment by brylie** [comment]
Based on the number of underlying questions, I am estimating that we will continue this in Sprint 1. Also, we need to clarify whether it is desirable or necessary to have two collections `Projects` and `ProjectDetails`, which seem to have duplicate data.

**Comment by leosa83** [comment]
We determined we wont go for separate collections initally.
