### ISSUE TITLE
Fixed Size singeProject html

### ISSUE THREAD

**Issue by leosa83** [refugeetech/platform#122]
The singleProject template outputs html that resizes based on the content. This messes up the flow when some are a bit larger than most others. 
# Definition of done
- [ ] Give singleProject html templates fixed size regardless if mobile or other screen

**Comment by Angamanga** [comment]
@leosa83 please check pull-request 133

**Comment by leosa83** [comment]
Removed this from 0.2

**Comment by Angamanga** [comment]
Closed by PR#133
