### ISSUE TITLE
Link to a typeform for signing up for the projecthub

### ISSUE THREAD

**Issue by leosa83** [refugeetech/platform#124]
# Definition of done
- [x] Developed the questions
- [x] Created the typeform  (http://tinyurl.com/rt-jointhehub)
- [x] Hardcoded the link in the code 
  - [x] Landing page "Get involved" buttons" 
# Benchmark

https://docs.google.com/forms/d/1jb9J2GUuXmrQswnQK-TVDJwNZc0hnd4VmEq_wlExcjo/viewform

**Comment by leosa83** [comment]
This is the link to the typeform: http://tinyurl.com/rt-jointhehub
@Shahin89 @miladf feedback

**Comment by leosa83** [comment]
Have assigned you @Angamanga

**Comment by Angamanga** [comment]
:+1:

**Comment by leosa83** [comment]
closed by #182
