### ISSUE TITLE
Add schema migration support to project

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#128]
As we continue development, some of our changes affect the project data structure. In order to update the data structure for existing deployments, some sort of migration needs to take place. Add schema migration support to the project and require that any project data structure changes include a corresponding migration process.

**Comment by leosa83** [comment]
This will be needed asap. There is another datastructure change in #111.

**Comment by leosa83** [comment]
The datastructure is basically set for now - we need some reviewing of it though. Can you review @brylie the schemas and ask the hard questions so we can clean it up before implementing migration support.

**Comment by brylie** [comment]
On second thought, the project doesn't need migration support until the first schema change. If the data structure seems stable, I recommend waiting until this feature is needed.
