### ISSUE TITLE
Adjustment of projects in singleProjects.html

### ISSUE THREAD

**Issue by Angamanga** [refugeetech/platform#134]
Make each project align as described in mockup, https://projects.invisionapp.com/share/HQ540EQ2S#/screens/118855239.

Every project now takes up the whole screen (col-12)(issue #122). This is a temporary fix made in commit https://github.com/refugeetech/platform/tree/a4271005c9574a5b68a6e9cc734749299a5145e3, since the adjustment of projects was not good at that point (projects jumping to the right at larger screen-sizes).

**Comment by leosa83** [comment]
Thanks @Angamanga
