### ISSUE TITLE
Searchbar

### ISSUE THREAD

**Issue by leosa83** [refugeetech/platform#135]
# Searchbar
- [ ] Close by clicking on the close button developed by @modsmoss or by clicking on the searchbutton again
- [ ] Reset searchbar when route occurs
- [ ] Search by pressing enter outside of /projects (no auto complete) => route to /projects?search=****

**Comment by leosa83** [comment]
im conflicted about this one if we are only having a couple of projects there is no meaning in having a functional search button. Whats your input @Angamanga ?

**Comment by Angamanga** [comment]
@leosa83 Hopefully we will have lots of projects in the future, but as for milestone 0.2, we might not need to prioritize it?

**Comment by leosa83** [comment]
Thats what im thinking , but if we have a searchbutton in the navbar that doesnt do anything , wouldnt it be weird?

**Comment by Angamanga** [comment]
Ok, so the search button is only for the projects, not all content? Then we might consider commenting the search button out for this milestone and add it when there are more projects present?

**Comment by leosa83** [comment]
Yes , lets do that . Whats your input @miladf ? @Davito163 ?
