### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by leosa83** [refugeetech/platform#136]
# Footer
- [x] Copy the appearance from https://projects.invisionapp.com/share/HQ540EQ2S#/screens/118594700
  - [x] Reuse some of the html for the footer from www.refugeetech.com
- [x] 'Press inquires' link => /press
- [x] Remove 'Work Forum'
- [x] Slack Community link with slack font-awesome 
- [x] Facebook Forum link with Facebook font-awesome

**Comment by virre** [comment]
How should copyright information be presented as on current page or suggestions (e.g "(c) 2016" or "(c) 2016 Refugee Tech" )  and should it really be other colors then rest of right aligned footer content

For that matter should FA links really be the read color. The design is for text links and not font-awesome versions. 

However basic branch with most of it created in branch feature-issue136-footer

**Comment by virre** [comment]
But except above as far as I can see this would be ready for a pull-request.

**Comment by leosa83** [comment]
Ok nice Virre! Regarding your comment. Lets go with how the design looks like for now. Please submit a PR if you think its ready. I will try to review it during the hackathon tomorrow while you will be hacking away on  important stuff :)

**Comment by leosa83** [comment]
this has been closed and merged
