### ISSUE TITLE
Style landingpage to match mockup

### ISSUE THREAD

**Issue by virre** [refugeetech/platform#141]
Currently the landing page is mostly a place holder
- [x] Create page accoridng to mockup: https://projects.invisionapp.com/share/J353G8DCW#/screens/118594700 
  - [x] Create html template in accordance with mockup. 
  - [x] Create styles to match mockup.
- [ ] Develop content @Shahin89 
  There is possible reuseable elements and style at Refugeetech.com

**Comment by Angamanga** [comment]
@virre do you need help with this issue?

**Comment by leosa83** [comment]
There is still some issues left; i created margins for each section but there should be non. Mobile adapations with bootstrap col-\* classes, and other things still to be figured out

**Comment by leosa83** [comment]
Will pass it back to you know @virre
