### ISSUE TITLE
About us Page

### ISSUE THREAD

**Issue by leosa83** [refugeetech/platform#148]
# About us page
- [x] Look and feel like on mockup
  https://projects.invisionapp.com/share/HQ540EQ2S#/screens/118594703
- [ ] Develop the text @Shahin89 
- [ ] Compose a video loop then convert to [gfycat](http://gfycat.com/about)
  - [ ] Choose the content @Davito163 @Shahin89 @Jonathan-Fristedt
  - [ ] Cut and compose @Jonathan-Fristedt + (Andreas)
  - [ ] Quality assurance @miladf 
  - [ ] Convert to Giphly @Jonathan-Fristedt
- [ ] Post the Giphly in the comments section here @Jonathan-Fristedt

**Comment by Angamanga** [comment]
@leosa83 according to the mockup, there should be a movie playing on the page, do we have a movie to use?

**Comment by leosa83** [comment]
No not yet , we will use a picture initially

**Comment by Angamanga** [comment]
I am wondering about the navbar on the about us page. It looks like it is transparent on the mock-up, compared to the other pages where it is white. Is it supposed to be like that or is it ok to keep it like it is on the other pages? I am unsure if it is possible to fix a specific style to the navbar on this page without making a new navbar?

**Comment by leosa83** [comment]
Yes good question: No we are sticking with our navbar design atm; we might go for tranparency later.

**Comment by Angamanga** [comment]
I cannot find the last photo in the Hello-lets-be-friends section, is that available somewhere?

**Comment by leosa83** [comment]
![gfx_intro](https://cloud.githubusercontent.com/assets/710548/13060568/dc6e6336-d432-11e5-8d73-113e0f6e51d2.jpg)
Here it is

**Comment by Angamanga** [comment]
Thanks!

**Comment by leosa83** [comment]
Merged

**Comment by jonathan** [comment]
@jonathan is not Andreas. It's me. :)

You probably want to change that.

**Comment by leosa83** [comment]
Will do :) @jonathan
