### ISSUE TITLE
Convert tabs to spaces (2) in project files

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#149]
There are several files in our project that use tabs, or four spaces, for each level of indentation. Convert indentation in all files to use two spaces per indent level.
# Criteria
- [x] `projects/view/client/projectProfile/beAPart/beAPart.css` contains two spaces per level of indentation, instead of tabs
- [x] `projects/view/client/rtProject/rtProjectInfoSection.css` contains two spaces per level of indentation, instead of tabs
- [x] all other files contains two spaces per level of indentation, instead of tabs

**Comment by brylie** [comment]
Great! I will help out here.

**Comment by leosa83** [comment]
Perf! I just pushed some changes to the issue branch.
