### ISSUE TITLE
Choose CSS framework for project

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#15]
In order to quickly design a responseive User Interface, we can choose from one of several available CSS frameworks. Choosing a CSS framework also means we can use integration packages from the Meteor Atmosphere.

Frameworks include:
- Bootstrap
- Polymer
- Semantic UI
- ...

It may be worth considering which framework(s) have the broadest support from the Meteor ecosystem.

**Comment by leosa83** [comment]
@davidpaulsson is there anyone you prefer/recommend?

**Comment by davidpaulsson** [comment]
TBH I'm no fan of frameworks and prefer to write CSS (SASS/SCSS) from scratch just utilizing smaller libs via npm (like resets etc). All these things just makes life bloated. They're great for a quick start and certainly have their place in the eco system, but are by no means any help when developing a GUI based on a unique design and most times you just have to fight the framework.

**Comment by brylie** [comment]
I think we should start with a framework, specifically the Bootstrap Framework. There are a lot of Meteor packages that include Bootstrap, so our project may inherit it as a requirement regardless.

We can look at the practicalities of assembling and designing CSS from scratch, including shivs, resets, etc., but for now I think a Framework is more beneficial than costly.

**Comment by davidpaulsson** [comment]
I strongly disagree, but go ahead :)

**Comment by brylie** [comment]
With what do you disagree?

**Comment by brylie** [comment]
Other than the premise?

**Comment by leosa83** [comment]
So what if we start with a framework to set things up and then go for the basic style of fronting you propose, if that is the teams preference at that time?

**Comment by brylie** [comment]
To make a fair comparison, lets determine what you propose. What libs would you include from npm? What is the compiled size of one or more themes you have built from scratch?

I.e. we are trying to get off the ground quickly here and there are several packages, including Bootstrap, that help us scaffold an MVP. 

I am interested in weighing the alternatives, and am no way insisting that the project will stick with Bootstrap forever.

**Comment by brylie** [comment]
@leosa83 :+1:

**Comment by davidpaulsson** [comment]
I'm just saying that bending a front end framework such as bootstrap to fit a custom design is, in my experience, more troublesome than just writing the styles from scratch.

**Comment by brylie** [comment]
Right, I understand better now. Lets see how we can keep Bootstrap from colliding with your design work :-)

**Comment by leosa83** [comment]
I have to point something out.
David will be our main fronter doing the designs and everything on Jekyll using low level fronting. When that is set up, and the styles and interactions are stable, only then would we copy it over to the platform in Meteor. So there will be a transition phase where we mold bootstrap to the frontend designed for the Jekyll site. After this phase it will be easy to use bootstrap as the design work has already been "completed", and you wont need to "wrestle" with the framework while developing your design. Or am i understanding this wrong?

**Comment by brylie** [comment]
Alright, I have added the Bootstrap 3 framework. Please be aware of Bootstrap 3 naming conventions, so that we can avoid clashing. Also, consider blending with and extending some of the Bootstrap 3 features, so that we can benefit from the development time that has been invested in the Bootstrap community.
