### ISSUE TITLE
Add code style guide to project

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#153]
In order to promote consistency in project sourcecode, add a code style guide to the project root. Include explanations of why certain conventions are adopted for the project, so that developers can have a better understanding of the intentions behind each suggested convention.
# Criteria
- [ ] Project contains code styleguide in markdown format
- [ ] code styleguide contains basic conventions for coders to follow
  - [ ] whitespace
  - [ ] semantics
- [ ] Code styleguide contains explanations of why each style convention is useful for this project

**Comment by leosa83** [comment]
:+1:
