### ISSUE TITLE
Start using Meteor.User

### ISSUE THREAD

**Issue by leosa83** [refugeetech/platform#155]
WORK IN PROGRESS
As a project owner
I would like to edit project details
so that i can update the content published in the project hub

As a project owner
I would like to administer user roles for my project
So that i can collaborate with others

**Comment by leosa83** [comment]
I assigned you @brylie since you could set this up real quick while i would need to do some research

**Comment by brylie** [comment]
Ok. Will you clarify the issue description a bit more?

**Comment by brylie** [comment]
@leosa83 will you please describe this issue using the [template from our contributing guide](https://github.com/refugeetech/platform/blob/develop/CONTRIBUTING.md#submitting-issues)?

**Comment by brylie** [comment]
It would help to have a description of what we want to achieve in general terms. Don't worry too much about technical details for now. We can sort those out during development.

**Comment by leosa83** [comment]
Ok :)
