### ISSUE TITLE
Add section: Hello lets be friends to landing page

### ISSUE THREAD

**Issue by leosa83** [refugeetech/platform#168]
The last section in this mockup: https://projects.invisionapp.com/share/J353G8DCW#/screens/118594700
# Definition of Done
- [x] add the file sectionHelloFriends.html and sectionHelloFriends.css to landing/client folder
- [x] create template with the same name
- [x] style in specific to section in css file and html structure in the html file using bootstrap semantics
- [x] Looks according to mockup

**Comment by Angamanga** [comment]
I am developing this for the about-page and it can be used on the landing page as well.

**Comment by leosa83** [comment]
Perfekt!

**Comment by Angamanga** [comment]
I put it in a directory in the main-directory instead since it will probably be used on several pages.

**Comment by leosa83** [comment]
Looks nice :)
