### ISSUE TITLE
cleanup: remove boiler plate code and deactivate unused routes

### ISSUE THREAD

**Issue by leosa83** [refugeetech/platform#178]
All navbar buttons that are not used should be commented out
All routes not used should be commented out

**Comment by Angamanga** [comment]
Does this apply to buttons as well?

**Comment by Angamanga** [comment]
@leosa83 I noticed that all buttons on landing-page routes to #involved. Is it ok to change to the correct route instead (where a route exists)? Its not a part of this issue but I thought I can fix it while I am checking the routes anyway...
