### ISSUE TITLE
Create copy for all pages and sections

### ISSUE THREAD

**Issue by leosa83** [refugeetech/platform#179]
@miladf @Shahin89 @jonathan
- [ ] [Landing page ](https://projects.invisionapp.com/share/HQ540EQ2S#/screens/118594700)
  - [ ] Copy for Our process section:
    - [ ] Change "Knowledge hub" column to something else and create copy
    - [x] Change "Projecthub" column to something else and create copy (already done: check out https://github.com/refugeetech/platform/blob/feature-copywriting/landing/client/sectionOurProcess.html and search for "RT Projects")
  - [x] Copy for The journey section (copy directly from refugetech.com ?)
- [ ] [About us page](https://projects.invisionapp.com/share/HQ540EQ2S#/screens/118594703)
- [x] [What we do page](https://projects.invisionapp.com/share/HQ540EQ2S#/screens/118594701) (Copy directly from refugeetech.com?)

**Comment by leosa83** [comment]
@miladf @Shahin89

**Comment by miladf** [comment]
@Shahin89 När kan vi bli klara med detta?
