### ISSUE TITLE
Section "whate theyre saying about us"

### ISSUE THREAD

**Issue by leosa83** [refugeetech/platform#181]
Style according to this mockup the section "What theyre saying about us"
https://www.dropbox.com/s/9jcfr3ze6gkg7vd/RT_Start_012_1440_DT.png?dl=0

(ive already handled the below @Shahin89 )
- [x] Collect all our media appearances in a spreadsheet @Shahin89 
- [x] Post the link to the spreadsheet in the comments section here @Shahin89

**Comment by leosa83** [comment]
@miladf  @Shahin89 Can you post here all links to media articles on RT?

**Comment by leosa83** [comment]
Working on the feature-181 branch, almost done with html and css. CSS help wanted

**Comment by Shahin89** [comment]
Internetworld: http://internetworld.idg.se/2.1006/1.647356/teknik-integration
Sveriges radio - Nordegren & Epstein http://sverigesradio.se/sida/artikel.aspx?programid=4058&artikel=6325671
Metro: https://issuu.com/metro_sweden/docs/20151211_se_stockholm/3?e=0
Sveriges radio: http://sverigesradio.se/sida/artikel.aspx?programid=103&artikel=6290852
DI digital: http://digital.di.se/artikel/techinsats-till-flyktingar
Resumé: http://www.resume.se/nyheter/artiklar/2015/12/11/hackaton-pa-byragolvet-ska-forenkla-nyanlandas-etablering/
Industrifonden: http://www.industrifonden.se/aid
Mobilestories: http://mobilestories.se/de-vill-lösa-flyktingkrisen-med-teknik
