### ISSUE TITLE
Populate initial backlog

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#2]
The project needs a starting backlog. Break down the MVP document into small tasks. Prioritize tasks according to urgency, sequence, and importance.

**Comment by leosa83** [comment]
Have broken down the MVP in the document https://github.com/refugeetech/platform/blob/develop/TASKS_BREAKDOWN.md

**Comment by leosa83** [comment]
It could definitely be refined but it lets us create some initial issues in the backlog.

**Comment by brylie** [comment]
Alright, thanks. I will add some of these tasks to the Github issue queue (backlog).
