### ISSUE TITLE
Create ProjectStages collection and relationship(s)

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#23]
Project stages can be managed through the User Interface, if they have a collection as a backend. 

If the project stages list may change over time, and it is not desirable to hard-code project stages into the system, add a  `ProjectStages` collection. This will then necessitate a relationship between ProjectStages and any related entities, such as Projects.

**Comment by leosa83** [comment]
At the moment we will only have two different statuses of projects: under development, released. This will change with time when we do better segmentation of projects.

Based on this; would you use ProjectStages as a collection at the moment? @brylie

**Comment by brylie** [comment]
We decided to hard code this into the schema.
