### ISSUE TITLE
Add 140 character limit to projectShort field

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#24]
The Projects schema contains a field called `projectShort`. It is desirable to enforce a character limit on this field, so that it falls within a certain limit. 
# Task
- [ ] Add 140 character limit to projectShort field, via `max` attribute
# Related

Related issue #12

**Comment by leosa83** [comment]
It should be: 140 characters

**Comment by yboulkaid** [comment]
PR for this : #34
