### ISSUE TITLE
Add Date picker widget to project startupDate field

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#26]
The Project startupDate field currently displays a text area on Firefox. It may be desirable to add a date picker widget to the field, so that people enter dates in the desired format. Choose an autoForm date picker, install it, and add it to the field.

**Comment by leosa83** [comment]
Datepickers are really dependent on the full UX design of the application. We could implement one just for us to input real projects, as we will use fake data tools for testing, but im not sure it will be worth the trouble at the moment. So this one is a low prio atm.

**Comment by leosa83** [comment]
Lets go ahead with this. Do you wanna take this one @loxtank ?

I would go for this one: https://github.com/aldeed/meteor-autoform-bs-datepicker/ that packages the bootstrap datepicker widget: http://eternicode.github.io/bootstrap-datepicker

**Comment by 2ECC71** [comment]
Yes, I'll take this

**Comment by brylie** [comment]
@loxtank thanks!
