### ISSUE TITLE
Add CONTRIBUTING.md to project

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#36]
In order to help new developers learn how to contribute, we can add a CONTRIBUTING.md to the project.
# Definition of done
- [x] CONTRIBUTING.md file exists in project
- [x] CONTRIBUTING.md contains:
  - [x] Gitflow instructions - explaining naming conventions and optional Gitflow extension
  - [x] Filestructure used in project
  - [x] Packages used
  - [x] Frameworks used

**Comment by leosa83** [comment]
Should the file contain what i added to description @brylie ?

**Comment by leosa83** [comment]
According to #22:
This project is using a feature module organization pattern. Please use the following, or similar, file structture:

/ (project root)
problemCategories/
both/
collections/
collection.js
schema.js
permissions.js
client/
templates/
templateName.html
templateName.js
server/
methods.js
publications.js

**Comment by leosa83** [comment]
added the file to development branch , has only filestructure at the moment

**Comment by leosa83** [comment]
@brylie It would be great to have this issue done soon as the interest to help out is increasing. Let me know what i can do to help you get this issue closed asap. Thanks.

**Comment by brylie** [comment]
Well, the task can be considered done for now. We can update the contributing instructions as need in the future.

**Comment by leosa83** [comment]
I didnt see you had edited the file. Looks good. Lets just add to the Packages description before closing this issue fully.

**Comment by brylie** [comment]
What do you want to add to packages? Is it relevant to new contributors or could it be added to readme?

**Comment by leosa83** [comment]
I just want them to have easy access to necessary documentation to the packages used.

**Comment by brylie** [comment]
I have added a packages section and mentioned the Meteor framework.
