### ISSUE TITLE
Upload the problem identification workshop report in the documentation folder

### ISSUE THREAD

**Issue by leosa83** [refugeetech/platform#39]
[problem_identification_workshop_report.pdf](https://github.com/refugeetech/platform/files/54450/problem_identification_workshop_report.pdf)

**Comment by brylie** [comment]
You can use the [documentation repository](https://github.com/refugeetech/documentation) for this text. Also, do you have the document in plain text format? It would be helpful to convert the text to markdown.

**Comment by leosa83** [comment]
Great! Will be uploading a markdown format when i have the docx format. Will use this tool: http://word-to-markdown.herokuapp.com/

**Comment by brylie** [comment]
@leosa83 status update?

**Comment by leosa83** [comment]
This is done. Havent been able to convert to an open format though. Will be looking at this farther ahead.
