### ISSUE TITLE
Create entity-relationship diagram for MVP data structure

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#5]
Create an [entity-relationship diagram](https://en.wikipedia.org/wiki/Entity%E2%80%93relationship_model#Entity.E2.80.93relationship_modeling) based on the MVP specification. This diagram will serve as a design reference model for the application data structure.
## Examples

![artist performs song](https://camo.githubusercontent.com/05b0808ff3ce44326bfe320ce7fee75fa128d5c8/68747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f7468756d622f332f33642f4572642d656e746974792d72656c6174696f6e736869702d6578616d706c65312e7376672f36343070782d4572642d656e746974792d72656c6174696f6e736869702d6578616d706c65312e7376672e706e67)

![Employee ssn](https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Erd-entity-with-attribute.svg/640px-Erd-entity-with-attribute.svg.png)
# Definition of done
- [x] Diagram includes MVP entities (nouns)
- [ ] Diagram includes MVP relationships (verbs)

**Comment by brylie** [comment]
@leosa83 will you please add your initial UML diagram to this task? If possible, convert it to SVG, so that we can easily make changes.

**Comment by leosa83** [comment]
Will be using ArgoUml for this. Unfortunately ArgoUml doesnt have an Undo functionality (!) so i lost all ive been working with for a couple of hours :(

**Comment by leosa83** [comment]
Have been mocking with the different stages and corresponding entities.
1. Is the MVP project hub without request
2. Is mvp project hub
3. Is crowdsourcing capabilities.

![erdiagram_ls_01](https://cloud.githubusercontent.com/assets/710548/12187584/65c41558-b5ad-11e5-9818-e3c8d407c02a.png)

**Comment by brylie** [comment]
Great work. The ER diagram doesn't need so much detail. Just the entities in the system and their relationships.

**Comment by brylie** [comment]
Some examples:

![Artist song](https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Erd-entity-relationship-example1.svg/640px-Erd-entity-relationship-example1.svg.png)

![Employee ssn](https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Erd-entity-with-attribute.svg/640px-Erd-entity-with-attribute.svg.png)

**Comment by brylie** [comment]
Basically, which need a concept map of how to design the system. We can make UML diagrams and schemad as follow up tasks.

**Comment by mark-mcevoy** [comment]
How about something like this? I'm still getting my head around the requirements so will take a few attempts :) (By the way I couldn't upload an svg file, github wouldn't allow it).

![er diagram - project hub](https://cloud.githubusercontent.com/assets/12165681/12217317/19468520-b6fd-11e5-8e74-cd5c1191314f.png)

**Comment by leosa83** [comment]
Great!

My feedback:

. Use the Request to encapsulate needs relationship. => Project makes
requests that requires skills and or proffesions. Check out my previous
comment (https://github.com/refugeetech/platform/issues/5#issuecomment-169858473) and the entities I've used there.
. Project targets one or several problem categories rather than beeing
described by them.

lör 9 jan 2016 6:18 em Mark McEvoy notifications@github.com skrev:

**Comment by mark-mcevoy** [comment]
Great thanks for the feedback! I have updated the diagram as necessary.

Some notes:
- I have kept profession and skills as seperate entities, as I think it would be difficult to define a profession with a certain subset of skills. For example a web developer is a profession, but skills for one web developer might be javascript, html, css, while another might be ASP.NET, Sql Server.
- I have added a many-to-many relationship between problem and problem categories. This is a complex relationship and needs to be further devbeloped. the question is if we need it for the MVP?

![er diagram - project hub](https://cloud.githubusercontent.com/assets/12165681/12221257/446198b2-b793-11e5-8236-2ca0d9bf284a.png)

**Comment by leosa83** [comment]
This is great!

Feedback:
- Having skill and profession as separate entities is sound and also something suggested in my previous comment i previously referred to: https://github.com/refugeetech/platform/issues/5#issuecomment-169858473
- You are correct that modelling the Problem relationships is not something we need to have in the MVP. I have previously explained this aswell (https://github.com/refugeetech/platform/issues/5#issuecomment-169858473 ; Step 1 => first release , Step 2 => MVP).
- Another feedback on the diagram is that a Project also targets specific Problems

Thanks,

Keep it coming :)

**Comment by brylie** [comment]
Wow! Nice work. This helps to clarify our system model.

**Comment by brylie** [comment]
@mark-mcevoy go ahead and upload the SVG file to the `documentation` repository, and put it in a sub-folder called `planning`. Make sure you are working in a branch of the `develop` branch, and open a Pull Request by comparing your branch with `develop`. We can assist with the pull request, if needed :-)

**Comment by mark-mcevoy** [comment]
Updated diagram to include relationship between Project and Problem. 

I have created a pull request with the diagram added in svg format, please see https://github.com/refugeetech/documentation/pull/2

![er diagram - project hub](https://cloud.githubusercontent.com/assets/12165681/12333718/37563a54-baf6-11e5-8493-662fcf00bba6.jpg)

**Comment by leosa83** [comment]
Great!  could you 1. Upload a diagram called mvpdiagram not including
problems. And 2. A diagram including problems, challenges, solutions,
ideas. The second diagram we will be needing soon .. I will create an issue
for the second diagram . So for the pull request upload the first one
instead (without problems).  Sorry for the inconvenience.

tors 14 jan 2016 7:40 em Mark McEvoy notifications@github.com skrev:

**Comment by brylie** [comment]
PR merged for initial diagram. Great work!

**Comment by leosa83** [comment]
@brylie I guess you didnt agree with my comment?

**Comment by brylie** [comment]
@leosa83 I thought you were creating a follow-up issue for improvements. The diagram provided in the PR is a great start.

**Comment by leosa83** [comment]
Ok i see!
Youre right its better to create a follow up issue for everything brought up in my comment, instead of changing the PR.
Thanks
