### ISSUE TITLE
Add social media links to mainFooter template

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#53]
The `mainFooter` template now has links/icons for social media (Twitter and Facebook). However, the links are not active.
# Task
- [ ] Determine actual links for RefugeeTech social media
  - [ ] Facebook
  - [ ] Twitter
- [ ] Update `mainFooter` template to include proper links

**Comment by Angamanga** [comment]
I can take this one!

**Comment by Angamanga** [comment]
Please check pull request from feature/issue53
