### ISSUE TITLE
Determine standup time and frequency

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#6]
The team should meet relatively frequently to coordinate efforts. Determine a time and schedule that works for everyone to have standups. These meetings should happen at least twice weekly and be no longer than 15 minutes.

**Comment by leosa83** [comment]
I think that we should have three weekly standups and one planning meeting every/first monday of the sprint. What do you think? =propose> Standups fridays , wednesdays and mondays. Planning meeting is for everyone interested but mainly for me and brylie. Then i would mainly communicate whats was planned during the planning meeting those days standups and planning meeting same day.

**Comment by Angamanga** [comment]
That sounds like a good idea! However, tuesdays and thursdays would be better for me until the end of january.

**Comment by leosa83** [comment]
That works fine for me! => Monday planning + standup, Tuesday standup, thursday standup, friday standup for those who can. Too much?
