### ISSUE TITLE
Add dynamic shrinking effect to navigation bar

### ISSUE THREAD

**Issue by leosa83** [refugeetech/platform#67]
Enhance the navigation menu with dynamic resizing.
# Related issues
- **Blocker**: This issue is a follow up to issue #71.
- **Parent**: This issue is created based on mockup in issue #70
# Instructions
- Create CSS rules using bootstrap
- Determine method for dynamic resizing
- Add dynamic resizing JavaScript and/or CSS rules
# Definition of Done
- [x] When scroll down on the front page,the navigation menu shrinks from 4.5em to 3.5em

**Comment by leosa83** [comment]
Man kan även ladda up resources

**Comment by brylie** [comment]
I recommend using relative values for layout, such as `em` or `rem`. Specifically, 55px and 75px are rather arbitrary, and could easily be expressed in relative values: 
- 75px: 4.5em or 4.5rem
- 55px: 3.5em or 3.5rem

These values are based on a 16px root or parent font size, which is reasonably easy to read.

**Comment by modsmoss** [comment]
Great @brylie ! Will start using relative units wherever possible. (everywhere but borders I believe)

I started to work on #67 on a local branch, but was never able to push it back up to github. Maybe someone can help me with this? (access denied)

When I did this I created a new folder main > client > _header_
In the header folder I put _navbar.html_, _navbar.css_ and _navbar.js_ 

Would this be the preferred way to structure the files, or should we keep a main js-file for frontend stuff?
Or is there anyway to concatenate the js-files (like the css) so we don't get another request for each little section in the code structure?

**Comment by brylie** [comment]
@modsmoss what repository were you attempting to push to?

**Comment by brylie** [comment]
@modsmoss you should have write access now.

**Comment by brylie** [comment]
Keeping all the files in the same folder _main / client / header/_ is conventional. Lets stick with it for now.

**Comment by brylie** [comment]
However, you are probably working on our landing page, which is defined in [/landing/client/](https://github.com/refugeetech/platform/tree/develop/landing/client)

**Comment by modsmoss** [comment]
platform. I cloned it and switched to a new branch. After commits I did `git push origin feature-issue67`

I did this from my other computer, where I first was logged in as another user when I cloned. But I switched to _modsmoss_. I will try again from another computer..

**Comment by brylie** [comment]
Please also give your feature branch a meaningful name. E.g. `feature/navigation-menu-dynamic-resize`

**Comment by modsmoss** [comment]
Sure, will do. I thought the issue would describe and branch name refer. But I guess I got that wrong

**Comment by brylie** [comment]
Good thought, there are just times where I am scanning the branch names without the issue numbers memorized.

**Comment by brylie** [comment]
@modsmoss lest go ahead and assign you to this issue and #71.
