### ISSUE TITLE
Create Projects collection filtering functions

### ISSUE THREAD

**Issue by 2ECC71** [refugeetech/platform#68]
#### User Story

As a user i want to filter the projects shown according to two arguments:
- Location
- Challenge category
#### Definition of done
- [x] Two dropdowns appear on project page
- [x] Dropdowns are automatically populated with values from Projects collection.
- [x] When default values are selected, all projects from Projects collection are shown on page.
- [x] When value in dropdown is selected, projects that match filter are shown on page.

**Comment by 2ECC71** [comment]
@brylie Perhaps we could use this package?
https://atmospherejs.com/doctorpangloss/filter-collections

**Comment by leosa83** [comment]
Area of expertise will not be possible until Requests collection has been defined and implemented - this is the second phase of the mvp. Will modify the issue accordingly.

**Comment by brylie** [comment]
@loxtank good find! Lets give it a try.

**Comment by brylie** [comment]
I have also used a [reactive-table package](https://github.com/aslagle/reactive-table) in a different project. In the reactive table view, I added [select menus to filter the table](https://github.com/GeriLife/wellbeing/blob/develop/client/views/activities/activities.html#L10-L20).

**Comment by 2ECC71** [comment]
problemCategory is done.
when i try to filter on postalAddress.country meteor crashes and tells me postalAddress is undefined.
@brylie

**Comment by 2ECC71** [comment]
Exception from sub projects/easySearch id nYB5qWbLpZ7qyGbsn TypeError: Cannot set property 'country' of undefined
I20160121-23:25:07.520(1)?     at MongoDBEngine.EasySearch.Index.engine.EasySearch.MongoDB.selector (projects/collections/collection.js:21:40)
I20160121-23:25:07.520(1)?     at MongoDBEngine.callConfigMethod (lib/core/engine.js:50:19)
I20160121-23:25:07.520(1)?     at MongoDBEngine.getSearchCursor (lib/engines/mongo-db.js:79:25)
I20160121-23:25:07.520(1)?     at MongoDBEngine.search (lib/core/reactive-engine.js:104:19)
I20160121-23:25:07.521(1)?     at [object Object]._handler (lib/core/search-collection.js:173:43)
I20160121-23:25:07.521(1)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
I20160121-23:25:07.521(1)?     at [object Object]._.extend._runHandler (livedata_server.js:1023:17)
I20160121-23:25:07.521(1)?     at [object Object]._.extend._startSubscription (livedata_server.js:842:9)
I20160121-23:25:07.521(1)?     at [object Object]._.extend.protocol_handlers.sub (livedata_server.js:614:12)
I20160121-23:25:07.521(1)?     at livedata_server.js:548:43

**Comment by 2ECC71** [comment]
Aha, not possible to handle nested objects in easysearch:
https://github.com/matteodem/meteor-easy-search/issues/79
