### ISSUE TITLE
Add navigation menu to default layout

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#71]
The default layout needs a navigation menu, so that users can have consistent navigation throughout the site.
# Definition of done
- [x] Navigation menu exists in default layout
- [x] Navigation menu has links to primary pages
  - [x] Navigation links have hover state: Underline
  - [x] Navigation links are **bold** when linking to current page (using Bootstrap 'active' class)
- [x] Navigation menu is defined using Bootstrap semantics
- [x] Navigation menu is styled to meet the styleguide/mockups for the main page
# Resources

The `active` class can be automatically added to menu links using the [Active Route](https://github.com/zimme/meteor-active-route/) Meteor package.
# Related issue

The following issue is a follow up to this issue:
- #67 Interactive shrinking of navigation bar

**Comment by brylie** [comment]
Note, some of these styles are part of the Bootstrap framework, such as the 'active' link styling. Please stick as close to Bootstrap semantics as possible, extending the Bootstrap framework with your custom work.

**Comment by leosa83** [comment]
@Angamanga Could you do the remaining checkbox ?

**Comment by Angamanga** [comment]
@leosa83 sure!

**Comment by Angamanga** [comment]
I pulled this branch and noticed it still has auto publish turned on. Is it a reason for that or may I turn it off? @modsmoss @brylie @leosa83

**Comment by brylie** [comment]
We have removed autopublish, so please make sure it doesn't get re-added in future PRs.

**Comment by Angamanga** [comment]
ok, is the rest of this branch(feature-issue71-search-and-filter) merged into develop? In that case I can start a new branch instead. But if the rest of the functionality for this issue is still unmerged I guess I need to continue in this branch?

**Comment by leosa83** [comment]
@Angamanga Yes all of these checkboxes have been merged into develop im pretty sure

**Comment by Angamanga** [comment]
Good! I'll start a new branch then!

**Comment by Angamanga** [comment]
Maybe we should delete this branch then?

**Comment by leosa83** [comment]
Yes , when we have double checked that all commits have been merged.. if you can check it please do so..

**Comment by leosa83** [comment]
This was closed by PR #138
