### ISSUE TITLE
Add "Share" feature to front page

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#75]
In the front page mockup, there is a link to "Share" in the navigation menu. We need to design and add this feature.

For milestone 0.2 the share feature will only be the right side of this mockup:https://projects.invisionapp.com/share/HQ540EQ2S#/screens/124546663
# Definition of done
- [x] UI Wireframe exists showing result of clicking "Share" link in navigation menu <br> For milestone 0.2 the share feature will only be the right side of this (the left side is #84 )
  https://projects.invisionapp.com/share/J353G8DCW#/screens/124546663
- [x] "Share" link exists in navigation menu
- [x] "Share" link has curving arrow icon
- [x] [Carrot share](http://sharebutton.co/) library has been added to project
- [ ] "Share" link triggers CarrotShare user interface
- [ ] " Share" link uses the Meteor.absoluteUrl(), so that people share the project front page
- [ ] _optional_ enhance share feature to allow sharing specific page, if `absoluteUrl` does not contain current path
# Resources

* [CarrotShare](http://sharebutton.co/) is an [open source share button](https://github.com/carrot/share-button) that preserves user privacy. It fits in with the purpose and design of this feature.

**Comment by leosa83** [comment]
This is the share overlay: https://projects.invisionapp.com/share/J353G8DCW#/screens/124546663

**Comment by brylie** [comment]
@leosa83 please post a static image (e.g. jpeg or png) in the issue discussion.

**Comment by leosa83** [comment]
@modsmoss or @virre or @josefcarlsson Could you self assign this one?

**Comment by brylie** [comment]
I have updated the task description to include a practical suggestion for how to implement the feature.

**Comment by Angamanga** [comment]
I can give it a try!

**Comment by Angamanga** [comment]
@brylie I have added the Carrot share but I don't get it to work. Could you please take a look? Its row 27 in navbar.html and 36-53 in navbar.js.

**Comment by brylie** [comment]
@Angamanga to make code review easier, open a pull request from your branch by comparing against `develop`. Then, add the `needs work` tag to indicate that your PR is in progress. Note: be sure to add "Closes #75" in the title of your pull request.

**Comment by leosa83** [comment]
@Angamanga Is it possible for you to create the look and feel as in the mockup with a transparent overlay and all of that?

maybe this is better suited for you , @modsmoss or @virre , as there is some tricky frontend stuff here?

**Comment by brylie** [comment]
Merged and included in the 0.2 release! :-) Thanks @Angamanga.
