### ISSUE TITLE
Add search feature for Projects collection

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#77]
Create a basic search feature for the Projects collection.
# Definition of done
- [x] Search fields are chosen from projects collection
- [x] Search index is added to project (so that other fields, possibly from other collections, may be added to index)
- [ ] `ensureIndex` has been added to desired fields in Projects collection
- [x] The team is aware of the options for creating a search index spanning multiple collections
# Potential packages
- Meteor [Easy Search](http://matteodem.github.io/meteor-easy-search/getting-started/)
# Reference

The following articles may help when researching this feature:
- Meteor Capture: [Simple search pattern](http://meteorcapture.com/simple-search-pattern/)
- MeteorHacks: [Implementing an Instant Search Solution with Meteor](https://meteorhacks.com/implementing-an-instant-search-solution-with-meteor.html)
- MongoDB docs [db.collection.ensureIndex()](https://docs.mongodb.org/v3.0/reference/method/db.collection.ensureIndex/)

**Comment by leosa83** [comment]
I have found some bugs:
- adding new project using the interface doesnt reactively update the searchindex
  but activating the search will find a newly added project

**Comment by brylie** [comment]
@leosa83 is the search engine defined for the proper fields? Also, what is the source of the query? We need to make sure the UI is pulling data from a reactive source, so that things behave dynamically.
