### ISSUE TITLE
Add search feature to front page

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#78]
Based on issue #77, we will add a search button/user interface to the front page.
- [x] show searchResults and allProjects template dynamically based on if currently searching

**Comment by leosa83** [comment]
Enhancment needed:
- show searchResults and allProjects template dynamically based on if currently searching

**Comment by leosa83** [comment]
This can overcome the bug in #77

**Comment by leosa83** [comment]
@mark-mcevoy do you wanna continue on this one from feature-#78 branch? Check my latest commit messages regarding reseting searchbar state

**Comment by mark-mcevoy** [comment]
Ok @leosa83 I can take over.

**Comment by mark-mcevoy** [comment]
I didn't get too far with this but noticed a bug with searchbars.js:

``` javascript
window.setTimeout(function() {
    Session.set('willShowAutoSuggestion',false);
}, 100);
```

The timeout is too short for me, so the click.result doesn't fire in autoSuggestRoutes. I think these kind of timeouts are too risky, as the behaviour is too unreliable from user to user. We should do the blur event a different way, for example by having a document.onclick event and checking if .result was clicked, else search button, etc. Would probably be a more reliable way of hiding the search bar & results.

**Comment by leosa83** [comment]
I agree. Please do as you think is best.
Den 20 jan 2016 20:20 skrev "Mark McEvoy" notifications@github.com:

**Comment by brylie** [comment]
@mark-mcevoy have you checked for Meteor typeahead packages, or similar?

**Comment by brylie** [comment]
Also, this is a 0.3 milestone task. We still need to complete the [0.2 milestone tasks](https://github.com/refugeetech/platform/milestones/0.2), so efforts should be directed there for now.

**Comment by leosa83** [comment]
Yes thats true, i didnt realize that either.

**Comment by leosa83** [comment]
I think it might be easier to have routes for the  navbar aswell, potentially with differeent templates for each route.

**Comment by leosa83** [comment]
We have a search button in the navbar - we also have a working search feature. Some design topups could be done to the autosuggest though.
But should we disable search feature for 0.2 since we will only launch with three projects?
@brylie

**Comment by Angamanga** [comment]
About autocomplete, if that is still an issue, I recently used this library for autocomplete in a Meteor-project: https://leaverou.github.io/awesomplete/. It was kind of neat and straightforward! @mark-mcevoy @brylie

**Comment by brylie** [comment]
Looks great! Lets give it a try :-)
