### ISSUE TITLE
Create issues based on the Project profile page

### ISSUE THREAD

**Issue by leosa83** [refugeetech/platform#80]
# Description

This issue is about coordinating efforts to develop the Project profile page
# Parent issue
#70
# Design

![rt_hub_wf_009_1_articlepage_v4_dt](https://cloud.githubusercontent.com/assets/710548/12270780/145ac384-b958-11e5-832b-23a1386542f9.png)
## In the mockup

https://projects.invisionapp.com/share/J353G8DCW#/screens/125324195
# Definition of Done
- [ ] All aspects of the Project profile page have been issued from these designs
## Child Issues
- [ ] #81 - Implement MVP Project Profile feature

**Comment by leosa83** [comment]
I have submitted a pull request solving #81. For each template an issue can be created. So if you wanna work with a particular template make sure to create an issue beforehand and then create a feature branch to solve it. Remember to assign yourself to the issue before starting the work on it.

**Comment by brylie** [comment]
Marking this as resolved, since the issues have been created as part of issue #81
