### ISSUE TITLE
Implement Project Media feature

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#83]
As an extension of the Project Profile feature, started in issue #81, we want to add the ability to attach photographs to a project profile display. This feature needs design, planning, and implementation.

**Comment by mark-mcevoy** [comment]
I've done a little research, and think we could make use of this CollectionFS package to help us with the uploading and storing of images:

https://github.com/CollectionFS/Meteor-CollectionFS

Note that we would need to choose one of the following storage adapters (also meteor packages):
cfs:gridfs
cfs:filesystem
cfs:s3
cfs:dropbox

I've seen that filesystem can cause issues if we are hosting our site on Meteor's own test server.

Anyone got any opinions on all this? @brylie @leosa83 ?

**Comment by leosa83** [comment]
Great , i would use the adapter cfs:gridfs. Since we wont need to use cfs:filestystem we wont have any issues with meteors test servers: gridfs doesnt use the filesystem to store the files (as opposed to cfs:filesystem).

**Comment by leosa83** [comment]
closed by feature-#83 , great work @mark-mcevoy
