### ISSUE TITLE
Allow tags to be added to projects and create composite publcation

### ISSUE THREAD

**Issue by leosa83** [refugeetech/platform#86]
# Description

At the moment Tags are attributes of Projects collection. While searching through the tag cloud after projects related to a specific tag, it is helpful to have a relational data structure to search through.
By using reactive joins with the [reywood:publish-composite](https://github.com/englue/meteor-publish-composite/) package, it is possible to create such a datastructure without the need of extracting Tags as its own collection.
## Necessary for

Project Search functionality #77
# Related
## Sub task
#104 - add Select widget to Tags field in Add Project form
## Parent tasks
#77
#19

**Comment by leosa83** [comment]
@brylie review please

**Comment by leosa83** [comment]
It doesnt seem to work to do what i intended. Tags needs their own collection. Or we need to work out how to easily search through projects tags without the need of accessing every project every time.

**Comment by brylie** [comment]
Yes, we need a tags collection. Then, each project has a `tagIds` Array field. Publish composite is then used to ensure each project page has relevant tags available by publishing all related documents at once.

**Comment by leosa83** [comment]
Could you take over this issue brylie?

**Comment by leosa83** [comment]
@brylie Could you take over this issue brylie?

**Comment by brylie** [comment]
@leosa83 yep.

**Comment by leosa83** [comment]
Thanks!

**Comment by brylie** [comment]
I have started implementing the tags multi-select field. The collection publication may come afterwords.

**Comment by leosa83** [comment]
Great!

**Comment by brylie** [comment]
The composite publication, for tags at lease, may not be necessary. The current Pull Request (#105) denormalizes the data, so that the tags are stored in both the Tags collection and as an array of strings in the Project document. This was a compromise, since we were unable to figure out how to store the key for newly created tags, via the Selecgize.js widget.

**Comment by leosa83** [comment]
Ok lets go with that.
